import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import { LocalConnectorForm } from './LocalConnectorForm';
import { api } from '../lib/api';
vi.mock('@tauri-apps/plugin-dialog', () => ({ open: vi.fn() }));
vi.mock('../lib/api', () => ({ nativeAvailable: true, api: { saveLocalConnector: vi.fn() }, errorMessage: (error: Error) => error.message }));
describe('local connector configuration', () => {
  it('edits the same server and preserves configured arguments and credentials', async () => {
    vi.mocked(api.saveLocalConnector).mockClear().mockResolvedValue();
    const initial = { id: 'local-fixture', name: 'Original', executable: 'C:\\node.exe', workingDirectory: 'C:\\work', arguments: ['a b', ''], environment: { TOKEN: 'saved-secret' } };
    const onSaved = vi.fn().mockResolvedValue(undefined);
    render(<LocalConnectorForm initial={initial} onSaved={onSaved} onCancel={vi.fn()} />);
    expect(screen.getByLabelText('Argument 1')).toHaveValue('a b');
    expect(screen.getByLabelText('Argument 2')).toHaveValue('');
    expect(screen.getByLabelText('Environment name 1')).toHaveValue('TOKEN');
    expect(screen.getByLabelText('Environment value 1')).toHaveValue('saved-secret');
    expect(screen.getByLabelText('Environment value 1')).toHaveAttribute('type', 'password');
    fireEvent.click(screen.getByRole('button', { name: 'Show environment value 1' }));
    expect(screen.getByLabelText('Environment value 1')).toHaveAttribute('type', 'text');
    fireEvent.change(screen.getByLabelText('Name'), {target:{value:'Renamed'}});
    fireEvent.click(screen.getByText('Save local server'));
    await waitFor(() => expect(onSaved).toHaveBeenCalledOnce());
    expect(api.saveLocalConnector).toHaveBeenCalledWith({...initial, name:'Renamed'});
  });
  it('saves exact argument boundaries and clears credentials without launching', async () => {
    vi.mocked(api.saveLocalConnector).mockResolvedValue();
    const onSaved = vi.fn().mockResolvedValue(undefined);
    render(<LocalConnectorForm onSaved={onSaved} />);
    fireEvent.click(screen.getByText('Add a local MCP server'));
    fireEvent.change(screen.getByLabelText('Name'), { target: { value: 'Fixture' } });
    fireEvent.change(screen.getByLabelText('Executable path'), { target: { value: 'C:\\node.exe' } });
    fireEvent.change(screen.getByLabelText('Working directory'), { target: { value: 'C:\\work' } });
    fireEvent.click(screen.getByRole('button', { name: 'Add argument' }));
    fireEvent.click(screen.getByRole('button', { name: 'Add argument' }));
    fireEvent.change(screen.getByLabelText('Argument 1'), { target: { value: 'path with spaces' } });
    fireEvent.change(screen.getByLabelText('Argument 2'), { target: { value: '' } });
    fireEvent.click(screen.getByRole('button', { name: 'Add variable' }));
    fireEvent.change(screen.getByLabelText('Environment name 1'), { target: { value: 'TOKEN' } });
    fireEvent.change(screen.getByLabelText('Environment value 1'), { target: { value: 'fixture-secret' } });
    fireEvent.click(screen.getByText('Save local server'));
    await waitFor(() => expect(onSaved).toHaveBeenCalledOnce());
    expect(api.saveLocalConnector).toHaveBeenCalledWith(expect.objectContaining({ name: 'Fixture', arguments: ['path with spaces', ''], environment: { TOKEN: 'fixture-secret' } }));
    expect(screen.getByRole('status')).toHaveTextContent('Use Connect');
  });
  it('warns about duplicate environment names and keeps JSON editing available', async () => {
    vi.mocked(api.saveLocalConnector).mockResolvedValue();
    render(<LocalConnectorForm onSaved={vi.fn().mockResolvedValue(undefined)} />);
    fireEvent.click(screen.getByText('Add a local MCP server'));
    fireEvent.click(screen.getByRole('button', { name: 'Add variable' }));
    fireEvent.click(screen.getByRole('button', { name: 'Add variable' }));
    fireEvent.change(screen.getByLabelText('Environment name 1'), { target: { value: 'TOKEN' } });
    fireEvent.change(screen.getByLabelText('Environment name 2'), { target: { value: 'token' } });
    expect(await screen.findByRole('alert')).toHaveTextContent('Duplicate environment name');
    fireEvent.click(screen.getByRole('button', { name: 'Edit environment as JSON' }));
    expect(screen.getByLabelText('Environment variables (JSON object)')).toBeInTheDocument();
  });
});
